CREATE ROLE tw LOGIN ENCRYPTED PASSWORD 'md50403cc43f5778a16d4e272ee46ca5de7'
  SUPERUSER CREATEDB CREATEROLE REPLICATION
   VALID UNTIL 'infinity';
GRANT pg_monitor TO tw WITH ADMIN OPTION;
GRANT pg_read_all_settings TO tw WITH ADMIN OPTION;
GRANT pg_read_all_stats TO tw WITH ADMIN OPTION;
GRANT pg_signal_backend TO tw WITH ADMIN OPTION;
GRANT pg_stat_scan_tables TO tw WITH ADMIN OPTION;
